services:
  demain_dev_db:
    image: mariadb:10.11
    restart: unless-stopped
    env_file: ./.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST:     ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE:      ${DB_DATABASE}
      MYSQL_USER:          ${DB_USERNAME}
      MYSQL_PASSWORD:      ${DB_PASSWORD}
      APP_ENV:             ${DB_APP_ENV}
      APP_DEBUG:           ${DB_APP_DEBUG}
      APP_URL:             ${DB_APP_DEBUG}
      
      TZ: Europe/Madrid
    ports:
      - "3307:3306"            # ← dev accesible desde tu Mac
    volumes:
      - demain_dev_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - demain_net

  demain_prod_db:
    image: mariadb:10.11
    restart: unless-stopped
    env_file: ./.env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST:     ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE:      ${DB_DATABASE}
      MYSQL_USER:          ${DB_USERNAME}
      MYSQL_PASSWORD:      ${PROD_DB_PASSWORD}
      APP_ENV:             ${DB_APP_ENV}
      APP_DEBUG:           ${DB_APP_DEBUG}
      APP_URL:             ${DB_APP_DEBUG}
      TZ: Europe/Madrid
    ports:
      - "3308:3306"            # ← prod separado; no lo usará Laravel aún
    volumes:
      - demain_prod_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - demain_net

  demain_laravel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./stack.env
    depends_on:
      - demain_prod_db   
      - demain_dev_db 
    ports:
      - "8001:8000"
    # volumes:
    #   - ./:/var/www/html          # desarrollo con live-reload
    networks:
      - demain_net

volumes:
  demain_dev_db_data:
  demain_prod_db_data:

networks:
  demain_net:
    driver: bridge
